#!/usr/bin/env python

# This is a temporary shim for testing barrelseq.
# When the package is properly installed with ``pip``
# a similar shim is automatically generated by the setup.py
# script in this directory.

import barrelseq

barrelseq.command_line.main()
